export const data = [
    {
      name:"Application",
      child:[
        {
          name:"Adobe",
          child:[
            {
              name:"CrashReports",
              child:[]
            }, 
            {
              name:"Adobe Reader",
              child:[]
            }, 
            {
              name:"Update",
              child:[]
            }, 
            {
              name:"Temp",
              child:[]
            }, 
          ]
        },
        {
          name:"Microsoft",
          child:[
            {
              name:"Edge",
              child:[
                {
                  name:"Application",
                  child:[]
                }, 
                {
                  name:"MSEdgeRecovery",
                  child:[]
                }, 
              ]
            }, 
            {
              name:"EdgeCore",
              child:[
                {
                  name:"108.0.1462.45",
                  child:[]
                }, 
                {
                  name:"105.0.1454.97",
                  child:[]
                }, 
                {
                  name:"102.0.1752.25",
                  child:[]
                }, 
              ]
            }, 
            {
              name:"EdgeUpdate",
              child:[
                {
                  name:"1.3.185.21",
                  child:[]
                }, 
                {
                  name:"Download",
                  child:[]
                }, 
                {
                  name:"Install",
                  child:[]
                }, 
                {
                  name:"Offline",
                  child:[]
                }, 
              ]
            }, 
            {
              name:"EdgeWebView",
              child:[{
                name:"Application",
                child:[]
              }, ]
            }, 
            {
              name:"Temp",
              child:[
                {
                  name:"EYUV4B45",
                  child:[]
                }, 
              ]
            }, 
          ]
        },
        {
          name:"Chrome",
          child:[]
        },
        {
          name:"Realtek",
          child:[
            {
              name:"PCIE Lan",
              child:[
                {
                  name:"RTWLANE_Driver",
                  child:[]
                }, 
                {
                  name:"RTKModule",
                  child:[]
                }, 
              ]
            },
            {
              name:"Realtek Bluetooth",
              child:[]
            },  
          ]
        },
        {
          name:"HP",
          child:[
            {
              name:"Hp Support",
              child:[
                {
                  name:"Modules",
                  child:[]
                }, 
                {
                  name:"Resources",
                  child:[]
                }, 
                {
                  name:"Warranty",
                  child:[]
                }, 
              ]
            }, 
            {
              name:"HPX Support",
              child:[
                {
                  name:"Resources",
                  child:[]
                }, 
                {
                  name:"Warranty",
                  child:[]
                }, 
              ]
            }, 
            {
              name:"Shared",
              child:[
                {
                  name:"Wzlink",
                  child:[]
                }, 
              ]
            }, 
            {
              name:"Temp",
              child:[]
            }, 
          ]
        }
      ]
    },
    {
      name:"Program Files",
      child:[
        {
          name:"Autodesk",
          child:[
            {
              name:"Application Plugins",
              child:[
                {
                  name:"Direct3D9",
                  child:[]
                }, 
                {
                  name:"Direct3D10",
                  child:[]
                }, 
                {
                  name:"Direct3D11",
                  child:[]
                }, 
              ]
            }, 
            {
              name:"AutoCAD 2018",
              child:[
                {
                  name:"Drv",
                  child:[]
                }, 
                {
                  name:"en",
                  child:[]
                }, 
                {
                  name:"en-US",
                  child:[]
                }, 
                {
                  name:"Environments",
                  child:[]
                },
                {
                  name:"Express",
                  child:[]
                },
                
                
              ]
            }, 
            {
              name:"Autodesk ReCap",
              child:[
                {
                  name:"Fonts",
                  child:[]
                },
                {
                  name:"GeoMapHTML",
                  child:[]
                },
                {
                  name:"Help",
                  child:[]
                },
              ]
            }, 
            {
              name:"Autodesk Sync",
              child:[
                {
                  name:"Inventor Server",
                  child:[]
                },
                {
                  name:"Migrator",
                  child:[]
                },
                {
                  name:"MsiKeyFile",
                  child:[]
                },
                {
                  name:"platforms",
                  child:[]
                },
                {
                  name:"Schemes",
                  child:[]
                },
              ]
            }, 
          ]
        },
        {
          name:"Common Files",
          child:[
            {
              name:"Shared",
              child:[]
            },
            {
              name:"Designer",
              child:[]
            },
            {
              name:"Environments",
              child:[]
            },
            {
              name:"Epson",
              child:[]
            },
            {
              name:"System",
              child:[]
            },
            {
              name:"Dowloader",
              child:[]
            },
            {
              name:"macrovision",
              child:[]
            },
          ]
        },
        {
          name:"Docker",
          child:[
            {
              name:"cli-plugins",
              child:[]
            },
            {
              name:"Docker",
              child:[]
            },
          ]
        },
        {
          name:"Git",
          child:[
            {
              name:"bin",
              child:[]
            },
            {
              name:"cmd",
              child:[]
            },
            {
              name:"dev",
              child:[]
            },
            {
              name:"etc",
              child:[]
            },
            {
              name:"mingw64",
              child:[]
            },
            {
              name:"tmp",
              child:[]
            },
            {
              name:"usr",
              child:[]
            },
          ]
        },
        {
          name:"McAfee",
          child:[
            {
              name:"WebAdvisor",
              child:[]
            },
            {
              name:"WPS",
              child:[]
            },
          ]
        },
        {
          name:"HP",
          child:[
            {
              name:"Consent",
              child:[]
            },
            {
              name:"Documentation",
              child:[]
            },
            {
              name:"Privacy",
              child:[]
            },
            {
              name:"shared",
              child:[]
            },
          ]
        },
        {
          name:"Internet Explorer",
          child:[
            {
              name:"en-GB",
              child:[]
            },
            {
              name:"en-US",
              child:[]
            },
            {
              name:"Images",
              child:[]
            },
            {
              name:"SIGNUP",
              child:[]
            },
          ]
        },
      ]
    },
    {
      name:"System",
      child:[
        {
          name:"App Locker",
          child:[]
        },
        {
          name:"Best Practices",
          child:[]
        },
        {
          name:"Cat Root",
          child:[]
        },
        {
          name:"Speech",
          child:[]
        },
        {
          name:"Sysprep",
          child:[]
        },
        {
          name:"Tasks",
          child:[]
        },
        {
          name:"SMI",
          child:[]
        },
      ]
    }, {
      name:"Users",
      child:[
        {
          name:"Sala",
          child:[
            {
              name:"FIles",
              child:[]
            },
            {
              name:"Secret",
              child:[]
            },
            {
              name:"Class",
              child:[]
            },
          ]
        },
        {
          name:"Contacts",
          child:[
            {
              name:"DataSet",
              child:[]
            },
            {
              name:"en-GB",
              child:[]
            },
            {
              name:"Privacy",
              child:[]
            },
            {
              name:"Data",
              child:[]
            },
          ]
        },
        {
          name:"Downloads",
          child:[
            {
              name:"Resume",
              child:[]
            },
            {
              name:"Personal",
              child:[]
            },
          ]
        },
        {
          name:"Favorites",
          child:[
            {
              name:"en-GB",
              child:[]
            },{
              name:"Photos",
              child:[]
            },
            {
              name:"Videos",
              child:[]
            },{
              name:"Movies",
              child:[]
            },
          ]
        },
        {
          name:"Links",
          child:[
            {
              name:"Subbed",
              child:[]
            },{
              name:"Hollywood",
              child:[]
            },{
              name:"Tamil",
              child:[]
            },
          ]
        },
        {
          name:"Music",
          child:[
            {
              name:"Tamil",
              child:[]
            },
            {
              name:"Malayalam",
              child:[]
            },{
              name:"Hindi",
              child:[]
            },{
              name:"English",
              child:[]
            },
            {
              name:"Ar Rahman",
              child:[]
            },
          ]
        },
        {
          name:"PostMan",
          child:[
            {
              name:"en-GB",
              child:[]
            },
            {
              name:"en-GB",
              child:[]
            },
            {
              name:"en-GB",
              child:[]
            },
          ]
        },
        {
          name:"One Drive",
          child:[]
        },
      ]
    },
    {
      name:"Project",
      child:[
        {
          name:"Helper",
          child:[
            {
              name:"Envy",
              child:[]
            },
            {
              name:"Data",
              child:[]
            },
            {
              name:"Module",
              child:[]
            },
          ]
        },
        {
          name:"Source",
          child:[
            {
              name:"sourceData",
              child:[]
            },
            {
              name:"Related",
              child:[]
            },
            {
              name:"Module",
              child:[]
            },
          ]
        },
        {
          name:"react-native",
          child:[
            {
              name:"Entry",
              child:[]
            },
            {
              name:"DataModule",
              child:[]
            },
            {
              name:"Fibre",
              child:[]
            },
          ]
        },
        {
          name:"Webcode",
          child:[
            {
              name:"Project 1",
              child:[]
            },
            {
              name:"Project 2",
              child:[]
            },
            {
              name:"Project 3",
              child:[]
            },
          ]
        },
        {
          name:"Capstone",
          child:[
            {
              name:"Capstone 1",
              child:[]
            },
            {
              name:"Capstone 2",
              child:[]
            },
            {
              name:"Capstone 3",
              child:[]
            },
          
          ]
        },
      ]
    }

  ]